### ISSUE TITLE
Page Parse Error

### ISSUE THREAD

**Issue by perrinaz** [maoserr/epublifier#62] opened 2023-01-24 20:21 UTC
Version 1.4.16 installed 1/24/23

Attempted to parse from novelupdates, I keep getting a "Chapter page parsing error:" and nothing after to indicate what the error might be.  I tried using v1.2.0 and it worked fine.

**Comment by perrinaz** [comment] 2023-01-28 16:35
Firefox.  Sorry, I didn't realize there was a Chrome extension, too.

**Comment by maoserr** [comment] 2023-03-07 03:32
i'm not able to reproduce, let me know the specific page you're try ing

**Comment by perrinaz** [comment] 2023-03-07 13:59
Funny you should message me :)  I just had to revisit this because the extension auto-updated and I was having it again.

This is the LN I'm trying to epubify:

https://www.novelupdates.com/series/slave-harem-in-the-labyrinth-of-the-other-world-ln

**Comment by maoserr** [comment] 2023-03-07 20:19
I see the issue is a re-direct from the "CLICK HERE TO READ" link disallowing CORS scripts to retrieve contents, this would not work normally on any version, I'm not sure how 1.2 works, did you check that the actual compiled epub has content?

With the way this code is currently implemented, I'll have to see if there's something I can add to the request to allow the redirect

**Comment by perrinaz** [comment] 2023-03-07 20:36
I am!  I epubified from the beginning to whatever was released in Jan and read it.  I noticed the abrupt ending and when I went back to look, saw that more had been released which I epubified -- and finished reading today.  There was one spot in the original when it got a part out of order (something like 5,6,9,7,8,10,11 but not these actual numbers) but other than that there were no obvious errors... at least... there were occasional dropped words that attributed to marginal editing.  Anyway, epubified twice and read through both epubs.  I just had to use 1.2.

**Comment by maoserr** [comment] 2023-03-08 01:14
Hmm, I see, it's a security policy change that's affecting the page parser, unfortunately the  1.2 parser would not pass security review anymore. I'll have to come up with an alternative

**Comment by maoserr** [comment] 2023-04-30 21:12
I installed firefox and look at this error again. It looks like permissions for hosts sometimes gets disabled in the options. But latest update to firefox seems to have fixed it for me. I'm going to close this unless you're still seeing this issue.

**Closed by maoserr** 2023-04-30 21:12 UTC
