### ISSUE TITLE
Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by samanta-widjaja** [maoserr/epublifier#106] opened 2023-05-06 01:01 UTC
I want to get https://www.novelupdates.com/series/trash-of-the-counts-family/

A few days ago it was fine. But today it show error. I use the latest google chrome.

The main page of epublifier show "Page parsed as Novel Update Series (876 chapters)".
But when i click load chapter, it only show "Error: Could not establish connection. Receiving end does not exist." and no chapter was parsed

Help please

**Comment by maoserr** [comment] 2023-05-06 13:30
I'm not able to reproduce, what's your browser and extension version?

**Comment by wattyven** [comment] 2023-05-07 04:47
Can reproduce the error in Chrome 113.0.5672.64, extension version 2.0.24. 
Unable to reproduce the error in Firefox 112.0.2, same extension version (2.0.24). 

Screenshot of browser window when encountering the error (tab isolated for the purpose of screenshot) https://i.imgur.com/ptMgP8L.png

**Comment by wattyven** [comment] 2023-05-07 05:03
Additionally, parsing seems to be much slower with the new version. While parsing a series, after approximately 12 minutes, I managed to get through 68 chapters in Firefox version 2.0.24 before closing out as it was degrading browser performance to the point of all other tabs being unusable. 

Manually rolling back to version 1.4.16 in Chrome, and parsing the same series again, after approximately 2 minutes it's parsed ~250 chapters and counting already.

**Comment by maoserr** [comment] 2023-05-07 13:35
ok, thanks, I got it. I'm pushing out a new build, let me know if you still see the issue

**Comment by wattyven** [comment] 2023-05-07 18:12
Loaded up 2.0.29 in Chrome, appears to be working now, thank you!

**Comment by samanta-widjaja** [comment] 2023-05-08 01:08
i haven't tried it yet because the version in chrome webstore still 2.0.24

**Comment by samanta-widjaja** [comment] 2023-05-08 06:55
it worked, but i haven't closed it yet because the chrome webstore is still the old version

**Comment by maoserr** [comment] 2023-05-11 01:39
the extension eventually will get published, just the review process

**Closed by maoserr** 2023-05-11 01:39 UTC
